export const movieData = [
    'The Shawshank Redemption',
    'The Godfather',
    'The Godfather: Part II',
    'The Dark Knight',
    '12 Angry Men',
    'Schindler',
    'Pulp Fiction',
    'The Lord of the Rings: The Return of the King',
    'The Good, the Bad and the Ugly',
    'Fight Club',
    'The Lord of the Rings: The Fellowship of the Ring',
    'Forrest Gump',
    'Star Wars: Episode V - The Empire Strikes Back',
    'Inception',
    'The Lord of the Rings: The Two Towers',
    'One Flew Over the Cuckoo',
    'Goodfellas',
    'The Matrix',
    'Seven Samurai',
    'Star Wars: Episode IV - A New Hope',
    'City of God',
    'Se7en',
    'The Silence of the Lambs',
    'It',
    'Life Is Beautiful',
    'The Usual Suspects',
    'Léon',
    'Saving Private Ryan',
    'Spirited Away',
    'American History X',
    'Once Upon a Time in the West',
    'Interstellar',
    'Psycho',
    'The Green Mile',
    'Casablanca',
    'City Lights',
    'Untouchable',
    'Modern Times',
    'Raiders of the Lost Ark',
    'The Pianist',
    'The Departed',
    'Rear Window',
    'Terminator 2: Judgment Day',
    'Back to the Future',
    'Whiplash',
    'Gladiator',
    'The Prestige',
    'The Lion King',
    'Memento',
    'Apocalypse Now',
    'Alien',
    'The Great Dictator',
    'Sunset Boulevard',
    'r. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
    'Cinema Paradiso',
    'The Lives of Others',
    'Grave of the Fireflies',
    'Paths of Glory',
    'Blade Runner 2049',
    'Django Unchained',
    'The Shining',
    'WALL·E',
    'American Beauty',
    'The Dark Knight Rises',
    'Princess Mononoke',
    'Oldboy',
    'Aliens',
    'Witness for the Prosecution',
    'Once Upon a Time in America',
    'Das Boot',
    'Citizen Kane',
    'Dangal',
    'Vertigo',
    'North by Northwest',
    'Star Wars: Episode VI - Return of the Jedi',
    'Braveheart',
    'Reservoir Dogs',
    'M',
    'Requiem for a Dream',
    'Amélie',
    'Like Stars on Earth',
    'A Clockwork Orange',
    'Your Name',
    'Lawrence of Arabia',
    'Double Indemnity',
    'Amadeus',
    'Eternal Sunshine of the Spotless Mind',
    'Taxi Driver',
    'To Kill a Mockingbird',
    'Full Metal Jacket',
    'Dunkirk',
    '2001: A Space Odyssey',
    'Singin',
    'Toy Story 3',
    'Toy Story',
    'The Sting',
    '3 Idiots',
    'Bicycle Thieves',
    'Inglourious Basterds',
    'The Kid',
    'Snatch',
    'Monty Python and the Holy Grail',
    'Good Will Hunting',
    'The Hunt',
    'For a Few Dollars More',
    '.A. Confidential',
    'Scarface',
    'The Apartment',
    'Metropolis',
    'A Separation',
    'Rashomon',
    'Indiana Jones and the Last Crusade',
    'All About Eve',
    'Yojimbo',
    'My Father and My Son',
    'Up',
    'Batman Begins',
    'Some Like It Hot',
    'The Treasure of the Sierra Madre',
    'Unforgiven',
    'Downfall',
    'Die Hard',
    'Raging Bull',
    'Heat',
    'The Third Man',
    'Children of Heaven',
    'The Great Escape',
    'Ikiru',
    'Chinatown',
    'Pan',
    'My Neighbor Totoro',
    'Incendies',
    'Ran',
    'The Gold Rush',
    'The Secret in Their Eyes',
    'Judgement at Nuremberg',
    'Inside Out',
    'On the Waterfront',
    'The Bridge on the River Kwai',
    'Howl',
    'Room',
    'The Seventh Seal',
    'Lock, Stock and Two Smoking Barrels',
    'r. Smith Goes to Washington',
    'Blade Runner',
    'Casino',
    'A Beautiful Mind',
    'The Elephant Man',
    'Wild Strawberries',
    'V for Vendetta',
    'The Wolf of Wall Street',
    'The General',
    'Warrior',
    'Trainspotting',
    'Dial M for Murder',
    'Gran Torino',
    'Sunrise',
    'Gone with the Wind',
    'Andrei Rublev',
    'The Deer Hunter',
    'Fargo',
    'The Sixth Sense',
    'The Thing',
    'No Country for Old Men',
    'The Big Lebowski',
    'The Bandit',
    'Finding Nemo',
    'Tokyo Story',
    'There Will Be Blood',
    'Cool Hand Luke',
    'Rebecca',
    'Hacksaw Ridge',
    'Come and See',
    'La La Land',
    'Kill Bill: Vol I',
    'Rang De Basanti',
    'How to Train Your Dragon',
    'The Passion of Joan of Arc',
    'Mary and Max',
    'Gone Girl',
    'Into the Wild',
    'Shutter Island',
    'Logan',
    'It Happened One Night',
    'Life of Brian',
    'Wild Tales',
    'A Wednesday',
    'Platoon',
    'The Wages of Fear',
    'Hotel Rwanda',
    'Network',
    'In the Name of the Father',
    'Rush',
    'Stand by Me',
    'Persona',
    'Ben-Hur',
    'The Grand Budapest Hotel',
    'The 400 Blows',
    'Memories of Murder',
    '12 Years a Slave',
    'Mad Max: Fury Road',
    'Jurassic Park',
    'Million Dollar Baby',
    'Spotlight',
    'Stalker',
    'Butch Cassidy and the Sundance Kid',
    'Amores Perros',
    'The Truman Show',
    'Hachi: A Dog',
    'The Maltese Falcon',
    'The Princess Bride',
    'Nausicaä of the Valley of the Wind',
    'Before Sunrise',
    'The Nights of Cabiria',
    'Paper Moon',
    'Prisoners',
    'Harry Potter and the Deathly Hallows: Part 2',
    'The Grapes of Wrath',
    'Rocky',
    'Catch Me If You Can',
    'Touch of Evil',
    'Les Diaboliques',
    'Gandhi',
    'Donnie Darko',
    'Monsters, Inc.',
    'Star Wars: The Force Awakens',
    'Annie Hall',
    'The Terminator',
    'Barry Lyndon',
    'The Bourne Ultimatum',
    'The Wizard of Oz',
    'Groundhog Day',
    'La Haine',
    '8½',
    'Jaws',
    'The Best Years of Our Lives',
    'Twelve Monkeys',
    'Infernal Affairs',
    'The Help',
    'Paris, Texas',
    'In the Mood for Love',
    'Beauty and the Beast',
    'The Handmaiden',
    'The Battle of Algiers',
    'Sholay',
    'Pirates of the Caribbean: The Curse of the Black Pearl',
    'PK',
    'Dog Day Afternoon',
    'Dead Poets Society',
];
